export const GET_PROJECT_REQUEST ='GET_PROJECT_REQUEST';
export const GET_PROJECT_SUCCESS="GET_PROJECT_SUCCESS";
export const GET_PROJECT_ERROR="GET_PROJECT_ERROR";

export const CREATE_PROJECT_REQUEST ='CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS="CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_ERROR="CREATE_PROJECT_ERROR";

export const GET_SINGLE_PROJECT_REQUEST="GET_SINGLE_PROJECT_REQUEST";
export const GET_SINGLE_PROJECT_SUCCESS="GET_SINGLE_PROJECT_SUCCESS";
export const GET_SINGLE_PROJECT_ERROR="GET_SINGLE_PROJECT_ERROR";

export const EDIT_PROJECT_REQUEST="EDIT_PROJECT_REQUEST";
export const EDIT_PROJECT_SUCCESS="EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_ERROR="EDIT_PROJECT_ERROR";

export const DELETE_PROJECT_REQUEST="DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS="DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_ERROR="DELETE_PROJECT_ERROR";

export const CREATE_TODO_REQUEST="CREATE_TODO_REQUEST";
export const CREATE_TODO_SUCCESS="CREATE_TODO_SUCCESS";
export const CREATE_TODO_ERROR="CREATE_TODO_ERROR";

export const GET_TODO_REQUEST="GET_TODO_REQUEST";
export const GET_TODO_SUCCESS="GET_TODO_SUCCESS";
export const GET_TODO_ERROR="GET_TODO_ERROR";

export const UPDATE_TODO_REQUEST="UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS="UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_ERROR="UPDATE_TODO_ERROR";

export const DELETE_TODO_REQUEST="DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS";
export const DELETE_TODO_ERROR="DELETE_TODO_ERROR";



